version: '3'
services:
  node:
    build:
      context: .
      args:
        - NODE_ENV=development
    command: ../node_modules/.bin/nodemon -L ./src/index.js
    volumes:
      - .:/opt/node_app/app:delegated
      - ./package.json:/opt/node_app/package.json
      - ./package-lock.json:/opt/node_app/package-lock.json
      - notused:/opt/node_app/app/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - '80:3000'
      - '9229:9229'
      - '9230:9230'
    healthcheck:
      disable: true

volumes:
  notused:
